ingress:
  enabled: true
  className: "nginx"
  annotations:    
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: home.int.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - home.int.demo.catena-x.net

  image:
    repository: ghcr.io/catenax-ng/k8s-example-argo-cd-project